baseURL = 'https://kyries-notebook.netlify.app/'
languageCode = 'en-us'
title = 'My Research Journal'
theme = "archie"
copyright = "© Kyrie Doniz"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/kyriedoniz/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://www.github.com/donizk/"

[[params.social]]
name = "Personal Site"
icon = "link"
url = "https://kyriedoniz.netlify.app/"
